version: '{branch}-{build}'

only_commits:
 files:
   - .\appveyor\Maestro.Microsoft.DependencyInjection.yaml
   - .\src\Maestro.Microsoft.DependencyInjection\**
   - .\test\Maestro.Microsoft.DependencyInjection.Tests\**

image: Visual Studio 2017

before_build:
- cmd: dotnet restore .\src\Maestro.Microsoft.DependencyInjection\Maestro.Microsoft.DependencyInjection.csproj --force
- cmd: dotnet restore .\test\Maestro.Microsoft.DependencyInjection.Tests\Maestro.Microsoft.DependencyInjection.Tests.csproj --force

build_script:
- cmd: dotnet build .\src\Maestro.Microsoft.DependencyInjection\Maestro.Microsoft.DependencyInjection.csproj -c release
- cmd: dotnet build .\test\Maestro.Microsoft.DependencyInjection.Tests\Maestro.Microsoft.DependencyInjection.Tests.csproj -c release

test:
  assemblies:
    only:
    - '**\Maestro.Microsoft.DependencyInjection.Tests.dll'
